### ISSUE TITLE
Wrong usage of "keywords" changes document font size

### ISSUE THREAD

**Issue by koppor** [sieversMartin/LNI#14]
If a user uses `\keywords{xy}` instead of the `keywords` environment, the font size of the main text changes:

```
\documentclass[english]{lni}
\usepackage{mwe}
\begin{document}
\title{Title}
\author{Author}
\keywords{\blindtext}
\blinddocument
\end{document}
```

## \keywords

![grabbed_20161222-234919](https://cloud.githubusercontent.com/assets/1366654/21442903/4a70b8ee-c8a1-11e6-8db1-ccb05fb8493e.png)

## keywords environment

![grabbed_20161222-234741](https://cloud.githubusercontent.com/assets/1366654/21442857/0dd792cc-c8a1-11e6-89dd-38136f82985a.png)

**Comment by sieversMartin** [comment]
Please note, that there is no macro `\keywords`, but only an environment `keywords`. The same mistake is often made within the standard classes using `\abstract` which does not exist as a macro as well.

It does only work, because defining an environment `env` in LaTeX ends with two macros `\env` and `\endenv` internally.

So, by using `\keywords` you get the layout changes, but due to the missing `\endkeywords` the font setup is not reset. The same happens with the space in #13. 

I might however add a check to inform the author about it.

**Comment by sieversMartin** [comment]
I added a check.
